### ISSUE TITLE
`redirect_uri` not sent in callback phase if not configured explicitly

### ISSUE THREAD

**Issue by steos** [utf26/ueberauth_linkedin#1]
Without explicitly configuring the `redirect_uri` there is an error on the linkedin side during the callback phase when calling get_token! at: 

```
token = apply(module, :get_token!, [[code: code]])
```

At this point the linkedin server responds with a 400 error that the `redirect_uri` is missing. 
During the request phase the `redirect_uri` is set automatically though and it looks like this should work as well during the callback phase. I.e. changing the relevant code to use `with_redirect_uri` solves the problem:

```
args = [[code: code] |> with_redirect_uri(conn)]
token = apply(module, :get_token!, args)
```

**Comment by ricksonoliveira** [comment]
@steos Can you please tell me how I can bypass this to explicitly configure the `redirect_uri`?

I have my config.exs like this

```elixir
config :ueberauth, Ueberauth.Strategy.LinkedIn.OAuth,
  client_id: System.get_env("LINKEDIN_CLIENT_ID"),
  client_secret: System.get_env("LINKEDIN_CLIENT_SECRET"),
  redirect_uri: System.get_env("LINKEDIN_REDIRECT_URI")
```

But in my request I'm always getting:

`The redirect_uri does not match the registered value`

I took a look in the code and they seem to not be using the `:redirect_uri` value passed in the config.
I guess that's the issue you're reporting right?
Can you help on how to explicitly pass this config key?

**Comment by steos** [comment]
@ricksonoliveira From your error message it sounds more like the value is not matching whatever you configured on the linkedin side. Or maybe the env variable is not set correctly?

**Comment by ricksonoliveira** [comment]
@steos Actually it was causing this issue because I was using `127.0.0.1` and the callback was trying `localhost`. The real issue now is that in the request `/linkedin/v2/authorize` it's returning me this:

> Your LinkedIn Network Will Be Back Soon
We’ve notified our operations staff that you are having a problem reaching LinkedIn. We’ll get you reconnected soon.
You can leave this window open and we’ll automatically take you back to your LinkedIn home page in a few minutes.

> We apologize for the interruption.

And my callback isn't being triggered. Is there additional configs to set up? Unfortunately this lib is poor in documentation regarding config keys.

BTW I'm just using the same config as in the example of the README

**Comment by steos** [comment]
@ricksonoliveira It works for me with the correct redirect URI. Only difference to the config in the README in my setup is that I configured the scopes explicitly:

```ex
 linkedin: {Ueberauth.Strategy.LinkedIn, [default_scope: "openid profile email"]}
```

This should be the default anyway though, but maybe it's not quite working correctly without explicit config?

**Comment by ricksonoliveira** [comment]
I didn't need to do that, actually I just needed to verify my app on LinkedIn Developers. Sorry for taking your time and thank you!

**Comment by utf26** [comment]
#2 solves this.
